# Generated by Django 3.1.2 on 2020-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=50)),
                ('point', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
